version: '3.8'

services:
  ApiReniec-bk:
    image: sebast19/api-reniec-bk:latest  
    ports:
      - "8080:8080"  
    environment:
      DATABASE_URL: ${DATABASE_URL}          
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}